/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package udemclass;


public class App {
    public String getGreeting() {
        return "::: Hello World GIRL ::: --------- ";
        //estamos en rama prueba hacemos cambios
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        //cambio
    }//sadhajskhdaskhdakjdsa
}